knp_paginator:
    page_range: 5 # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page # Nom du paramètre utilisé pour la pagination dans l'URL
        sort_field_name: sort
        sort_direction_name: direction
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig' # Template par défaut
