security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: userEmail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\AppCustomAuthenticator
            custom_authenticators:
                - App\Security\AppCustomAuthenticator

            logout:
                path: logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: true
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/password_change, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/password, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: ROLE_USER }

