controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
qr_codes:
    path: /qr_codes/{filename}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '%kernel.project_dir%/public/qr_codes/{filename}'
        permanent: true
    requirements:
        filename: ".+"

