# config/services.yaml
parameters:
    paypal.client_id: '%env(PAYPAL_CLIENT_ID)%'
    paypal.secret: '%env(PAYPAL_SECRET)%'
    paypal.mode: '%env(PAYPAL_MODE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\PaypalService:
        arguments:
            $paypalClientId: '%paypal.client_id%'
            $paypalSecret: '%paypal.secret%'
            $paypalMode: '%paypal.mode%'