# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    mollie_api_key: '%env(MOLLIE_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Enregistre les classes de src/ en tant que services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Définition explicite de MollieService
    App\Service\MollieService:
        arguments:
            $mollieApiKey: '%env(MOLLIE_API_KEY)%'

